import argparse
import sqlite3
import pandas as pd

def query_to_float(db_path: str, stringa: str) -> float:
    conn = sqlite3.connect(db_path)
    stringa_clean = stringa.replace("'","''")
    myquery = f"select count( distinct string_value) conteggio from embedding_fulltext_search_content c join embedding_metadata m on c.id = m.id and m.key = 'EID'  where upper(c.c0) like upper('%{stringa_clean}%') "
    #print (myquery)

    cursor = conn.cursor()

    try:
        # Execute the query
        cursor.execute(myquery)
        # Fetch the single result
        result = cursor.fetchone()[0]
    finally:
        # Ensure the connection is closed
        conn.close()

    return result


db_path = '/storage/david/documenti/phd/articoli_analizzati/chroma/chroma.sqlite3'

def esegui(stringa: str):
    valore = query_to_float(db_path,stringa)
    print (stringa+";"+str(valore))


esegui ("academic performance")
esegui ("accuracy")
esegui ("admittance")
esegui ("age")
esegui (" ai ")
esegui ("analysis")
esegui ("analyze")
esegui (" ann ")
esegui ("artificial intelligence")
esegui ("artificial neural networks")
esegui ("aware")
esegui ("birthplace")
esegui ("boosting")
esegui ("causal inference")
esegui ("class imbalance")
esegui ("classification")
esegui ("classification problems")
esegui ("classifiers")
esegui ("cluster models")
esegui ("clustering algorithms")
esegui ("cognitive factors")
esegui ("completion intention")
esegui ("context")
esegui (" cost ")
esegui ("Cost-Sensitive")
esegui ("recommendation")
esegui ("credits")
esegui ("data analysis")
esegui ("data cleaning")
esegui ("data collection")
esegui ("data imbalance")
esegui ("data mining")
esegui ("data preprocessing")
esegui ("data reduction")
esegui ("data sampling")
esegui ("decision tree")
esegui ("dimensional reduction ")
esegui ("Drop%out")
esegui ("Drop out")
esegui ("Drop-out")
esegui ("dropout")
esegui ("dynamic features")
esegui ("early intervention")
esegui ("education policy")
esegui ("educational data mining")
esegui ("emir")
esegui ("ensemble")
esegui ("evaluation metrics")
esegui ("f1")
esegui ("factors")
esegui ("feature engineering")
esegui ("feature extraction")
esegui ("feature selection")
esegui ("features")
esegui ("financial aid")
esegui ("gender")
esegui ("gradient boosting")
esegui ("graduation")
esegui ("graduation prediction")
esegui ("higher education")
esegui ("identify%students")
esegui ("improve prediction accuracy")
esegui ("layer perceptron")
esegui ("learning analytics")
esegui ("logistic regression")
esegui ("machine learning")
esegui ("methods")
esegui ("metrics")
esegui ("modelling")
esegui ("missing values")
esegui ("naive bayes")
esegui ("natural language processing")
esegui ("nearest neighbor")
esegui ("neural network")
esegui ("nonlinear relationships")
esegui ("performance")
esegui ("performance measures")
esegui ("performance prediction")
esegui ("precision")
esegui ("predict")
esegui ("prediction model")
esegui ("predictive model")
esegui ("predictive system")
esegui ("prevent dropout")
esegui ("previous academic performance")
esegui ("principal component analysis")
esegui ("random forest")
esegui ("random oversampling")
esegui ("recall")
esegui ("recommender systems")
esegui ("retention")
esegui ("risk students")
esegui ("sensitive learning")
esegui ("sentiment analysis")
esegui ("smote")
esegui ("stacking models")
esegui ("student behavior")
esegui ("student demographics")
esegui ("student persistence")
esegui ("student retention")
esegui ("support vector machines")
esegui ("time management")
esegui ("understanding")
esegui ("year failure")
esegui ("ann%neural network%ann")
esegui ("neural network%ann")
esegui ("ann%neural network")
esegui ("shap")
esegui ("explain")
esegui ("explainable")
esegui ("interpret")
esegui ("interpretable")
esegui ("OECD")
